import { useState } from "react";
import {
  FolderOpen,
  FileCode,
  FileText,
  File,
  Database,
  GitBranch,
  Download,
  Copy,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  ChevronRight,
  ChevronDown,
  Package,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  generateScaffold,
  downloadScaffoldZip,
  ScaffoldResponse,
  ScaffoldFile,
} from "@/services/scaffold";
import { ProjectContextInput } from "@/services/database";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function langIcon(language: string) {
  switch (language) {
    case "python": return <FileCode className="h-3.5 w-3.5 text-blue-400" />;
    case "typescript": return <FileCode className="h-3.5 w-3.5 text-cyan-400" />;
    case "sql": return <Database className="h-3.5 w-3.5 text-orange-400" />;
    case "json": return <File className="h-3.5 w-3.5 text-yellow-400" />;
    case "markdown": return <FileText className="h-3.5 w-3.5 text-purple-400" />;
    case "yaml": return <GitBranch className="h-3.5 w-3.5 text-green-400" />;
    default: return <File className="h-3.5 w-3.5 text-muted-foreground" />;
  }
}

function langColor(language: string) {
  switch (language) {
    case "python": return "bg-blue-500/10 text-blue-400 border-blue-500/20";
    case "typescript": return "bg-cyan-500/10 text-cyan-400 border-cyan-500/20";
    case "sql": return "bg-orange-500/10 text-orange-400 border-orange-500/20";
    case "json": return "bg-yellow-500/10 text-yellow-400 border-yellow-500/20";
    case "markdown": return "bg-purple-500/10 text-purple-400 border-purple-500/20";
    case "yaml": return "bg-green-500/10 text-green-400 border-green-500/20";
    default: return "bg-muted text-muted-foreground";
  }
}

// ─── File Preview ─────────────────────────────────────────────────────────────

function FilePreview({ file }: { file: ScaffoldFile }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(file.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([file.content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = file.path.split("/").pop() || "file.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-2 h-full">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-2">
          {langIcon(file.language)}
          <span className="text-sm font-mono text-foreground">{file.path}</span>
          <Badge variant="outline" className={`text-[10px] px-1.5 ${langColor(file.language)}`}>
            {file.language}
          </Badge>
        </div>
        <div className="flex gap-1.5">
          <Button size="sm" variant="ghost" className="h-7 px-2 text-xs" onClick={handleCopy}>
            {copied ? <CheckCircle2 className="h-3.5 w-3.5 text-green-400" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied" : "Copy"}
          </Button>
          <Button size="sm" variant="ghost" className="h-7 px-2 text-xs" onClick={handleDownload}>
            <Download className="h-3.5 w-3.5 mr-1" />
            Download
          </Button>
        </div>
      </div>
      <pre className="flex-1 overflow-auto rounded-lg border border-border bg-muted/30 p-3 text-xs leading-relaxed font-mono text-foreground whitespace-pre-wrap">
        <code>{file.content}</code>
      </pre>
      <p className="text-[10px] text-muted-foreground">Generated by: {file.generated_by}</p>
    </div>
  );
}

// ─── File Tree ────────────────────────────────────────────────────────────────

function buildTree(files: ScaffoldFile[]): Record<string, ScaffoldFile[]> {
  const dirs: Record<string, ScaffoldFile[]> = { "__root__": [] };
  for (const f of files) {
    const parts = f.path.split("/");
    if (parts.length === 1) {
      dirs["__root__"].push(f);
    } else {
      const top = parts[0];
      if (!dirs[top]) dirs[top] = [];
      dirs[top].push(f);
    }
  }
  return dirs;
}

function FileTree({
  files,
  selectedFile,
  onSelect,
}: {
  files: ScaffoldFile[];
  selectedFile: ScaffoldFile | null;
  onSelect: (f: ScaffoldFile) => void;
}) {
  const [expandedDirs, setExpandedDirs] = useState<Set<string>>(new Set(["__root__", "backend", "frontend", "docs"]));
  const tree = buildTree(files);

  const toggleDir = (dir: string) => {
    setExpandedDirs((prev) => {
      const next = new Set(prev);
      next.has(dir) ? next.delete(dir) : next.add(dir);
      return next;
    });
  };

  const renderFile = (f: ScaffoldFile) => (
    <button
      key={f.path}
      onClick={() => onSelect(f)}
      className={`flex items-center gap-2 w-full px-2 py-1 rounded text-left text-xs hover:bg-muted/50 transition-colors ${
        selectedFile?.path === f.path ? "bg-brand-soft text-brand" : "text-muted-foreground hover:text-foreground"
      }`}
    >
      {langIcon(f.language)}
      <span className="truncate font-mono">{f.path.split("/").pop()}</span>
    </button>
  );

  const rootFiles = tree["__root__"] || [];
  const dirKeys = Object.keys(tree).filter(k => k !== "__root__").sort();

  return (
    <div className="flex flex-col gap-0.5 text-xs select-none">
      {rootFiles.map(renderFile)}
      {dirKeys.map(dir => (
        <div key={dir}>
          <button
            onClick={() => toggleDir(dir)}
            className="flex items-center gap-1.5 w-full px-2 py-1 rounded text-left hover:bg-muted/50 transition-colors text-foreground"
          >
            {expandedDirs.has(dir)
              ? <ChevronDown className="h-3 w-3 text-muted-foreground" />
              : <ChevronRight className="h-3 w-3 text-muted-foreground" />}
            <FolderOpen className="h-3.5 w-3.5 text-yellow-400" />
            <span className="font-mono font-medium">{dir}/</span>
            <span className="ml-auto text-muted-foreground/60">{tree[dir].length}</span>
          </button>
          {expandedDirs.has(dir) && (
            <div className="ml-4 border-l border-border/50 pl-2 flex flex-col gap-0.5 my-0.5">
              {tree[dir].map(renderFile)}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

// ─── Stats Bar ────────────────────────────────────────────────────────────────

function StatsBar({ scaffold }: { scaffold: ScaffoldResponse }) {
  const dirs = new Set(scaffold.files.map(f => f.path.split("/")[0])).size;
  const langs = new Set(scaffold.files.map(f => f.language)).size;
  return (
    <div className="grid grid-cols-3 gap-3">
      {[
        { label: "Total Files", value: scaffold.total_files },
        { label: "Directories", value: dirs },
        { label: "Languages", value: langs },
      ].map(({ label, value }) => (
        <div key={label} className="rounded-lg border border-border bg-muted/20 p-3 text-center">
          <div className="text-2xl font-bold text-brand">{value}</div>
          <div className="text-xs text-muted-foreground mt-0.5">{label}</div>
        </div>
      ))}
    </div>
  );
}

// ─── Main Panel ───────────────────────────────────────────────────────────────

interface Props {
  context: ProjectContextInput;
  scaffold: ScaffoldResponse | null;
  onScaffoldGenerated: (data: ScaffoldResponse) => void;
}

export function ScaffoldPanel({ context, scaffold, onScaffoldGenerated }: Props) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedFile, setSelectedFile] = useState<ScaffoldFile | null>(null);

  const hasContext =
    context.requirements || context.architecture || context.database || context.documentation;

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await generateScaffold(context);
      onScaffoldGenerated(data);
      // auto-select first file for preview
      if (data.files.length > 0) setSelectedFile(data.files[0]);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Failed to generate project scaffold.";
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  const [downloadingZip, setDownloadingZip] = useState(false);

  const handleDownloadAll = async () => {
    if (!scaffold) return;
    setDownloadingZip(true);
    try {
      await downloadScaffoldZip(scaffold);
    } catch (err) {
      console.error("ZIP download failed:", err);
    } finally {
      setDownloadingZip(false);
    }
  };

  return (
    <div className="flex flex-col gap-4">
      {/* Header card */}
      <Card className="border-brand/20 bg-brand-soft/10">
        <CardHeader className="pb-3">
          <div className="flex items-start justify-between flex-wrap gap-3">
            <div>
              <CardTitle className="flex items-center gap-2 text-base">
                <Package className="h-4 w-4 text-brand" />
                Project Generator
              </CardTitle>
              <CardDescription className="mt-1">
                Deterministically assembles a complete, development‑ready project from the planning context.
                No LLM calls – pure template‑driven generation.
              </CardDescription>
            </div>
            <div className="flex gap-2">
              {scaffold && (
                <Button size="sm" variant="outline" onClick={handleDownloadAll} disabled={downloadingZip}>
                  {downloadingZip ? (
                    <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />
                  ) : (
                    <Download className="h-3.5 w-3.5 mr-1.5" />
                  )}
                  Download ZIP
                </Button>
              )}
              <Button
                size="sm"
                onClick={handleGenerate}
                disabled={loading || !hasContext}
                className="bg-brand hover:bg-brand/90"
              >
                {loading ? (
                  <><Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> Generating…</>
                ) : (
                  <><Package className="h-3.5 w-3.5 mr-1.5" /> Generate Project</>
                )}
              </Button>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
          <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
          {error}
        </div>
      )}

      {/* Not ready hint */}
      {!hasContext && !scaffold && (
        <div className="rounded-lg border border-border bg-muted/20 p-6 text-center text-sm text-muted-foreground">
          Complete the Requirements, Architecture, Database, and Documentation steps first, then generate the project.
        </div>
      )}

      {/* Results */}
      {scaffold && (
        <>
          {/* Summary banner */}
          <div className="flex items-start gap-2 rounded-lg border border-green-500/30 bg-green-500/10 p-3 text-sm text-green-400">
            <CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0" />
            <span>{scaffold.generation_summary}</span>
          </div>

          {/* Stats */}
          <StatsBar scaffold={scaffold} />

          {/* Explorer + Preview */}
          <div className="grid grid-cols-1 lg:grid-cols-[260px_1fr] gap-4">
            {/* File Tree */}
            <Card>
              <CardHeader className="pb-2 pt-3 px-3">
                <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  File Explorer
                </CardTitle>
              </CardHeader>
              <CardContent className="px-2 pb-3 overflow-y-auto max-h-[520px]">
                <FileTree
                  files={scaffold.files}
                  selectedFile={selectedFile}
                  onSelect={setSelectedFile}
                />
              </CardContent>
            </Card>

            {/* Code Preview */}
            <Card>
              <CardHeader className="pb-2 pt-3 px-4">
                <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  File Preview
                </CardTitle>
              </CardHeader>
              <CardContent className="px-4 pb-4 h-[520px] flex flex-col">
                {selectedFile ? (
                  <FilePreview file={selectedFile} />
                ) : (
                  <div className="flex-1 flex items-center justify-center text-sm text-muted-foreground">
                    Select a file from the explorer to preview its contents.
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Tree view */}
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm">Directory Tree</CardTitle>
            </CardHeader>
            <CardContent>
              <pre className="text-xs font-mono text-muted-foreground bg-muted/30 rounded-lg p-3 overflow-auto">
                {scaffold.tree_view}
              </pre>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
