import zipfile
import pytest
from fastapi.testclient import TestClient
from app.main import app
from app.models.scaffold import ScaffoldFile, ScaffoldResponse
from app.services.zip_service import ZipService

client = TestClient(app)

@pytest.fixture
def sample_scaffold_response() -> ScaffoldResponse:
    return ScaffoldResponse(
        project_name="Test App",
        tree_view="Test Project Structure",
        files=[
            ScaffoldFile(
                path="README.md",
                content="# Test Project\n\nGenerated by Blueprint.",
                language="markdown",
                generated_by="DocumentationAgent",
            ),
            ScaffoldFile(
                path="backend/app/main.py",
                content="from fastapi import FastAPI\napp = FastAPI()",
                language="python",
                generated_by="ScaffoldAgent (Project Generator)",
            ),
        ],
        total_files=2,
        generation_summary="Successfully generated test project foundation.",
    )

def test_zip_service_creates_valid_zip(sample_scaffold_response: ScaffoldResponse):
    zip_buffer = ZipService.create_zip_archive(sample_scaffold_response)
    assert zip_buffer is not None
    
    # Verify contents of zip file using standard zipfile module
    with zipfile.ZipFile(zip_buffer, "r") as zf:
        namelist = zf.namelist()
        assert "README.md" in namelist
        assert "backend/app/main.py" in namelist
        
        readme_content = zf.read("README.md").decode("utf-8")
        assert "# Test Project" in readme_content

def test_export_zip_endpoint_returns_200_stream(sample_scaffold_response: ScaffoldResponse):
    response = client.post("/agents/scaffold/export-zip", json=sample_scaffold_response.model_dump())
    assert response.status_code == 200
    assert response.headers["content-type"] == "application/zip"
    assert "attachment; filename=" in response.headers["content-disposition"]
    
    # Read the returned stream as zip
    zip_bytes = response.content
    import io
    with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as zf:
        assert "README.md" in zf.namelist()
