"""
export_service.py
─────────────────
Compiles the ProjectContext produced by the planning agents into a
professionally-styled PDF document following IEEE Standard formatting guidelines.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)
from reportlab.platypus.flowables import Flowable

from app.models.requirements import ProjectContext

PAGE_W, PAGE_H = A4
MARGIN = 2 * cm


# ─── Custom IEEE Page Borders and Canvas Callbacks ──────────────────────────

def _on_first_page(canvas, doc):
    """Draws simple cover borders/headers if necessary."""
    canvas.saveState()
    canvas.restoreState()


def _on_body_page(canvas, doc):
    """Draws the running headers/footers in traditional IEEE technical report style."""
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#7F8C8D"))
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, PAGE_H - 1.5 * cm, PAGE_W - MARGIN, PAGE_H - 1.5 * cm)
    
    # Running header
    canvas.setFillColor(colors.HexColor("#555555"))
    canvas.setFont("Times-Roman", 8)
    project = getattr(doc, "_project_name", "BLUEPRINT PROJECT REPORT")
    canvas.drawString(MARGIN, PAGE_H - 1.3 * cm, f"IEEE DESIGN SPECIFICATION: {project.upper()}")
    
    # Footer
    canvas.line(MARGIN, 1.5 * cm, PAGE_W - MARGIN, 1.5 * cm)
    canvas.drawString(MARGIN, 1.1 * cm, "Generated by BluePrint AI — SDLC Planner")
    canvas.drawRightString(PAGE_W - MARGIN, 1.1 * cm, f"Page {doc.page}")
    canvas.restoreState()


# ─── IEEE Style Typography ──────────────────────────────────────────────────

def _build_styles() -> dict:
    styles: dict = {}

    styles["ieee_title"] = ParagraphStyle(
        "ieee_title",
        fontName="Times-Bold",
        fontSize=24,
        textColor=colors.black,
        alignment=TA_CENTER,
        spaceAfter=15,
        leading=28,
    )
    styles["ieee_subtitle"] = ParagraphStyle(
        "ieee_subtitle",
        fontName="Times-Roman",
        fontSize=12,
        textColor=colors.HexColor("#333333"),
        alignment=TA_CENTER,
        spaceAfter=25,
        leading=16,
    )
    styles["ieee_author"] = ParagraphStyle(
        "ieee_author",
        fontName="Times-Roman",
        fontSize=10,
        textColor=colors.black,
        alignment=TA_CENTER,
        spaceAfter=40,
        leading=14,
    )
    styles["ieee_abstract_label"] = ParagraphStyle(
        "ieee_abstract_label",
        fontName="Times-BoldItalic",
        fontSize=10,
        textColor=colors.black,
        spaceAfter=4,
        leading=12,
    )
    styles["ieee_abstract_text"] = ParagraphStyle(
        "ieee_abstract_text",
        fontName="Times-Italic",
        fontSize=10,
        textColor=colors.black,
        alignment=TA_JUSTIFY,
        spaceAfter=20,
        leading=14,
    )
    styles["section_heading"] = ParagraphStyle(
        "section_heading",
        fontName="Times-Bold",
        fontSize=12,
        textColor=colors.black,
        alignment=TA_CENTER,
        spaceBefore=22,
        spaceAfter=10,
        leading=16,
    )
    styles["sub_heading"] = ParagraphStyle(
        "sub_heading",
        fontName="Times-BoldItalic",
        fontSize=11,
        textColor=colors.black,
        spaceBefore=14,
        spaceAfter=8,
        leading=14,
    )
    styles["body"] = ParagraphStyle(
        "body",
        fontName="Times-Roman",
        fontSize=10,
        textColor=colors.black,
        spaceAfter=8,
        leading=14,
    )
    styles["body_bold"] = ParagraphStyle(
        "body_bold",
        fontName="Times-Bold",
        fontSize=10,
        textColor=colors.black,
        spaceAfter=8,
        leading=14,
    )
    styles["code"] = ParagraphStyle(
        "code",
        fontName="Courier",
        fontSize=8.5,
        textColor=colors.HexColor("#2C3E50"),
        backColor=colors.HexColor("#F8F9F9"),
        spaceAfter=8,
        leading=12,
        leftIndent=15,
        rightIndent=15,
        borderPad=6,
    )
    styles["bullet"] = ParagraphStyle(
        "bullet",
        fontName="Times-Roman",
        fontSize=10,
        textColor=colors.black,
        spaceAfter=6,
        leading=14,
        leftIndent=20,
        bulletIndent=10,
    )
    styles["toc_item"] = ParagraphStyle(
        "toc_item",
        fontName="Times-Roman",
        fontSize=10,
        textColor=colors.black,
        spaceAfter=6,
        leading=14,
    )
    return styles


# ─── Content Helper Builders ────────────────────────────────────────────────

def _p(text: str, style: ParagraphStyle) -> Paragraph:
    safe = (text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return Paragraph(safe, style)


def _bullet_list(items: List[str], styles: dict) -> List[Flowable]:
    out: List[Flowable] = []
    for item in items:
        safe = (item or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        out.append(Paragraph(f"• {safe}", styles["bullet"]))
    return out


def _section_header(numeral: str, title: str, styles: dict) -> List[Flowable]:
    return [
        Spacer(1, 0.4 * cm),
        _p(f"{numeral}. {title.upper()}", styles["section_heading"]),
        Spacer(1, 0.2 * cm),
    ]


def _sub_header(letter: str, title: str, styles: dict) -> Flowable:
    return _p(f"{letter}. {title}", styles["sub_heading"])


def _code_block(sql: str, styles: dict) -> List[Flowable]:
    lines = (sql or "").split("\n")
    out = []
    for line in lines:
        safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        out.append(Paragraph(safe or "&nbsp;", styles["code"]))
    return out


def _build_cover(context: ProjectContext, styles: dict) -> List[Flowable]:
    project_name = "UNTITLED SYSTEM SPECIFICATION"
    overview = "This document presents the design specification, architecture, and database design produced under IEEE standards."
    if context.requirements:
        project_name = (context.requirements.project_name or project_name).upper()
        overview = context.requirements.project_overview or overview

    now = datetime.now().strftime("%B %d, %Y")

    flowables: List[Flowable] = [
        Spacer(1, 3 * cm),
        _p(project_name, styles["ieee_title"]),
        _p("SYSTEM ENGINEERING BLUEPRINT AND SRS DOCUMENTATION", styles["ieee_subtitle"]),
        Spacer(1, 1 * cm),
        _p("Prepared by: BluePrint Automated SDLC Agent Suite<br/>"
           f"Date: {now}<br/>"
           "Standards Compliance: IEEE Std 830-1998 / ISO 12207", styles["ieee_author"]),
        Spacer(1, 1.5 * cm),
        _p("Abstract", styles["ieee_abstract_label"]),
        _p(overview, styles["ieee_abstract_text"]),
        PageBreak(),
    ]
    return flowables


def _build_toc(context: ProjectContext, styles: dict) -> List[Flowable]:
    out: List[Flowable] = _section_header("I", "Table of Contents", styles)
    out.append(Spacer(1, 0.5 * cm))
    
    sections = []
    if context.requirements:  sections.append("II. Software Requirements Specification (SRS)")
    if context.architecture:  sections.append("III. System Architecture Design")
    if context.database:      sections.append("IV. Database Design and Schema Normalization")
    if context.documentation: sections.append("V. System Execution and Reference Documentation")

    for s in sections:
        out.append(_p(s, styles["toc_item"]))
        out.append(Spacer(1, 0.2 * cm))
    out.append(PageBreak())
    return out


def _build_requirements_section(req, styles: dict) -> List[Flowable]:
    out: List[Flowable] = _section_header("II", "Software Requirements Specification", styles)

    out.append(_sub_header("A", "Project Scope and Overview", styles))
    out.append(_p(req.project_overview, styles["body"]))
    out.append(Spacer(1, 0.3 * cm))

    if req.objectives:
        out.append(_sub_header("B", "System Objectives", styles))
        out.extend(_bullet_list(req.objectives, styles))
        out.append(Spacer(1, 0.3 * cm))

    if req.functional_requirements:
        out.append(_sub_header("C", "Functional Requirements", styles))
        out.extend(_bullet_list(req.functional_requirements, styles))
        out.append(Spacer(1, 0.3 * cm))

    if req.non_functional_requirements:
        out.append(_sub_header("D", "Non-Functional Requirements", styles))
        out.extend(_bullet_list(req.non_functional_requirements, styles))
        out.append(Spacer(1, 0.3 * cm))

    if req.user_roles:
        out.append(_sub_header("E", "User Roles & Personas", styles))
        out.extend(_bullet_list(req.user_roles, styles))
        out.append(Spacer(1, 0.3 * cm))

    if req.user_stories:
        out.append(_sub_header("F", "Use Case / User Story Breakdown", styles))
        out.append(_p("<b>TABLE I. USER STORY SPECIFICATION</b>", styles["body_bold"]))
        table_data = [["Role", "Desire", "Benefit"]]
        for story in req.user_stories:
            table_data.append([
                Paragraph(story.role or "", styles["body"]),
                Paragraph(story.desire or "", styles["body"]),
                Paragraph(story.benefit or "", styles["body"]),
            ])
        col_widths = [3 * cm, 7.5 * cm, 6 * cm]
        t = Table(table_data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#EAECEE")),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.black),
            ("FONTNAME",    (0, 0), (-1, 0), "Times-Bold"),
            ("FONTSIZE",    (0, 0), (-1, 0), 10),
            ("ALIGN",       (0, 0), (-1, 0), "LEFT"),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#BDC3C7")),
            ("TOPPADDING",  (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        out.append(t)
        out.append(Spacer(1, 0.5 * cm))

    if req.recommended_tech_stack:
        out.append(_sub_header("G", "Technology Stack Composition", styles))
        ts = req.recommended_tech_stack
        stack_data = [
            ["Layer", "Technology Profile"],
            ["Frontend Client",   ts.frontend   or "—"],
            ["Backend Application",    ts.backend    or "—"],
            ["Database Server",   ts.database   or "—"],
            ["Inference Engine",   ts.ai_framework or "—"],
        ]
        t2 = Table(stack_data, colWidths=[5 * cm, 11.5 * cm], repeatRows=1)
        t2.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#EAECEE")),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.black),
            ("FONTNAME",    (0, 0), (-1, 0), "Times-Bold"),
            ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#BDC3C7")),
            ("TOPPADDING",  (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        out.append(t2)
        out.append(Spacer(1, 0.4 * cm))

    if req.assumptions or req.constraints:
        out.append(_sub_header("H", "Assumptions and Constraints", styles))
        if req.assumptions:
            out.append(_p("<b>System Assumptions:</b>", styles["body_bold"]))
            out.extend(_bullet_list(req.assumptions, styles))
        if req.constraints:
            out.append(_p("<b>System Constraints:</b>", styles["body_bold"]))
            out.extend(_bullet_list(req.constraints, styles))

    out.append(PageBreak())
    return out


def _build_architecture_section(arch, styles: dict) -> List[Flowable]:
    out: List[Flowable] = _section_header("III", "System Architecture Design", styles)

    out.append(_sub_header("A", "High-Level Architecture Description", styles))
    out.append(_p(arch.high_level_architecture, styles["body"]))
    out.append(Spacer(1, 0.3 * cm))

    if arch.data_flow:
        out.append(_sub_header("B", "Information Flow & Core Mechanics", styles))
        out.append(_p(arch.data_flow, styles["body"]))
        out.append(Spacer(1, 0.3 * cm))

    if arch.folder_structure:
        out.append(_sub_header("C", "Logical Project Directory Structure", styles))
        out.extend(_code_block("\n".join(arch.folder_structure), styles))
        out.append(Spacer(1, 0.3 * cm))

    if arch.component_breakdown:
        out.append(_sub_header("D", "Component Decomposition", styles))
        for comp in arch.component_breakdown:
            out.append(_p(f"<b>Component: {comp.name}</b>", styles["body_bold"]))
            out.append(_p(comp.description or "", styles["body"]))
            if comp.dependencies:
                out.append(_p(f"<i>Dependencies:</i> {', '.join(comp.dependencies)}", styles["body"]))
            out.append(Spacer(1, 0.2 * cm))

    out.append(PageBreak())
    return out


def _build_database_section(db, styles: dict) -> List[Flowable]:
    out: List[Flowable] = _section_header("IV", "Database Design and Schema Normalization", styles)

    if db.database_overview:
        out.append(_sub_header("A", "Database Overview", styles))
        out.append(_p(db.database_overview, styles["body"]))
        out.append(Spacer(1, 0.3 * cm))

    if db.normalization_notes:
        out.append(_sub_header("B", "Normalization and Integrity Constraints", styles))
        out.append(_p(db.normalization_notes, styles["body"]))
        out.append(Spacer(1, 0.3 * cm))

    if db.relationships:
        out.append(_sub_header("C", "Entity-Relationship Cardinalities", styles))
        out.extend(_bullet_list(db.relationships, styles))
        out.append(Spacer(1, 0.3 * cm))

    if db.entities:
        out.append(_sub_header("D", "Entity Specifications", styles))
        for entity in db.entities:
            out.append(_p(f"<b>Table Schema: {entity.name}</b>", styles["body_bold"]))
            out.append(_p(entity.description or "", styles["body"]))
            if entity.attributes:
                attr_data = [["Attribute / Field"]]
                for attr in entity.attributes:
                    attr_data.append([Paragraph(attr or "", styles["body"])])
                t = Table(attr_data, colWidths=[PAGE_W - 2 * MARGIN - 1 * cm], repeatRows=1)
                t.setStyle(TableStyle([
                    ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#EAECEE")),
                    ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#BDC3C7")),
                    ("TOPPADDING",  (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]))
                out.append(t)
            
            pk_text = f"Primary Key: {entity.primary_key}" if entity.primary_key else ""
            fk_text = f"Foreign Keys: {', '.join(entity.foreign_keys)}" if entity.foreign_keys else ""
            if pk_text or fk_text:
                out.append(_p(f"<i>Keys:</i> {pk_text} { ' | ' + fk_text if fk_text else ''}", styles["body"]))
            out.append(Spacer(1, 0.4 * cm))

    if db.sql_schema:
        out.append(_sub_header("E", "ANSI-Compliant DDL Statements", styles))
        out.extend(_code_block(db.sql_schema, styles))

    out.append(PageBreak())
    return out


def _build_documentation_section(doc, styles: dict) -> List[Flowable]:
    out: List[Flowable] = _section_header("V", "System Execution and Reference Documentation", styles)

    if doc.project_overview:
        out.append(_sub_header("A", "System Execution Summary", styles))
        out.append(_p(doc.project_overview, styles["body"]))
        out.append(Spacer(1, 0.3 * cm))

    if doc.installation_guide:
        out.append(_sub_header("B", "Deployment & Installation Blueprint", styles))
        out.extend(_code_block(doc.installation_guide, styles))
        out.append(Spacer(1, 0.3 * cm))

    if doc.api_documentation:
        out.append(_sub_header("C", "API Interface Profiles", styles))
        out.append(_p(doc.api_documentation, styles["body"]))
        out.append(Spacer(1, 0.3 * cm))

    if doc.developer_notes:
        out.append(_sub_header("D", "Development Practices & Conventions", styles))
        out.append(_p(doc.developer_notes, styles["body"]))

    return out


# ─── Public API ───────────────────────────────────────────────────────────────

class ExportService:
    """Converts a :class:`ProjectContext` into an IEEE styled PDF document."""

    def generate_pdf(self, context: ProjectContext) -> bytes:
        buffer = io.BytesIO()
        styles = _build_styles()

        project_name = "BLUEPRINT PLAN"
        if context.requirements and context.requirements.project_name:
            project_name = context.requirements.project_name

        doc = BaseDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN,
            bottomMargin=MARGIN,
            title=f"IEEE SPECIFICATION: {project_name.upper()}",
            author="BluePrint AI Planner",
        )
        doc._project_name = project_name

        body_frame  = Frame(MARGIN, MARGIN, PAGE_W - 2 * MARGIN, PAGE_H - 2 * MARGIN)
        body_tpl  = PageTemplate(id="IEEE_Body", frames=[body_frame], onPage=_on_body_page)
        doc.addPageTemplates([body_tpl])

        story: List[Flowable] = []
        story.append(NextPageTemplate("IEEE_Body"))
        
        # Cover sheet / Abstract
        story.extend(_build_cover(context, styles))
        
        # Table of Contents
        story.extend(_build_toc(context, styles))

        if context.requirements:
            story.extend(_build_requirements_section(context.requirements, styles))

        if context.architecture:
            story.extend(_build_architecture_section(context.architecture, styles))

        if context.database:
            story.extend(_build_database_section(context.database, styles))

        if context.documentation:
            story.extend(_build_documentation_section(context.documentation, styles))

        doc.build(story)
        return buffer.getvalue()
