"""
File Generator
--------------
Builds the complete list of ``ScaffoldFile`` objects for a project given a
``GenerationContext``.

This module is purely deterministic – it contains **no** LLM calls. It maps
the structured metadata in ``GenerationContext`` to rendered file contents.
"""

from __future__ import annotations

import json
from datetime import date
from typing import List

from app.models.generation_context import GenerationContext
from app.models.scaffold import ScaffoldFile
from app.project_generator.loader import TemplateLoader
from app.project_generator.renderer import TemplateRenderer


class FileGenerator:
    """Converts a ``GenerationContext`` into a list of ``ScaffoldFile`` objects."""

    def __init__(self) -> None:
        self._loader = TemplateLoader()
        self._renderer = TemplateRenderer()

    def generate(self, ctx: GenerationContext) -> List[ScaffoldFile]:
        """Return all files that should be created for the project."""
        tpl_vars = self._build_template_vars(ctx)
        files: List[ScaffoldFile] = []

        files.extend(self._root_files(ctx, tpl_vars))
        files.extend(self._docs_files(ctx))
        files.extend(self._backend_files(ctx, tpl_vars))
        files.extend(self._frontend_files(ctx, tpl_vars))
        files.extend(self._database_files(ctx))
        files.extend(self._scripts_files(ctx, tpl_vars))
        files.extend(self._github_files(ctx, tpl_vars))
        files.extend(self._generated_summary(ctx, files))

        return files

    def _build_template_vars(self, ctx: GenerationContext) -> dict:
        routes_block = "\n".join(
            f"# {r.method} {r.path} - {r.description}" for r in ctx.api_routes
        ) or "# No routes defined yet"

        entities_block = "\n".join(
            f"# {e.name}: {', '.join(a['name'] for a in e.attributes)}"
            for e in ctx.entities
        ) or "# No entities defined yet"

        return {
            "project_name": ctx.project_name,
            "project_name_lowercase": ctx.project_name_slug,
            "project_overview": ctx.architecture_summary or f"A {ctx.backend_type} + {ctx.frontend_type} project.",
            "ai_framework": "Ollama",
            "backend_type": ctx.backend_type,
            "frontend_type": ctx.frontend_type,
            "database_type": ctx.database_type,
            "authentication": ctx.authentication,
            "routes_comment": routes_block,
            "entities_comment": entities_block,
            "year": str(date.today().year),
        }

    def _render(self, filename: str, vars: dict) -> str:
        try:
            raw = self._loader.load(filename)
            return self._renderer.render(raw, vars)
        except FileNotFoundError:
            return f"# Template '{filename}' not found – replace with actual content\n"

    def _root_files(self, ctx: GenerationContext, v: dict) -> List[ScaffoldFile]:
        files = []

        readme = ctx.readme_content or self._render("README.md.template", v) if "README.md.template" in self._loader.list_templates() else (
            f"# {ctx.project_name}\n\n{v['project_overview']}\n\n## Tech Stack\n"
            f"- **Frontend:** {ctx.frontend_type}\n- **Backend:** {ctx.backend_type}\n"
            f"- **Database:** {ctx.database_type}\n\n## Getting Started\n\n"
            "```bash\n# Backend\ncd backend && pip install -r requirements.txt\n"
            "uvicorn app.main:app --reload\n\n# Frontend\ncd frontend && npm install && npm run dev\n```\n"
        )
        files.append(ScaffoldFile(path="README.md", content=readme, language="markdown", generated_by="DocumentationAgent"))

        files.append(ScaffoldFile(
            path="CHANGELOG.md",
            content=f"# Changelog\n\n## [0.1.0] – {date.today()}\n### Added\n- Initial project scaffold generated by Blueprint.\n",
            language="markdown", generated_by="ScaffoldAgent (Project Generator)"
        ))
        files.append(ScaffoldFile(
            path="CONTRIBUTING.md",
            content=(
                f"# Contributing to {ctx.project_name}\n\n"
                "Thank you for your interest in contributing!\n\n"
                "## How to Contribute\n1. Fork the repository.\n2. Create a feature branch.\n"
                "3. Commit your changes.\n4. Open a Pull Request.\n"
            ),
            language="markdown", generated_by="ScaffoldAgent (Project Generator)"
        ))
        files.append(ScaffoldFile(
            path=".gitignore",
            content="venv/\n__pycache__/\n*.pyc\nnode_modules/\n.env\n.DS_Store\ndist/\nbuild/\n",
            language="text", generated_by="ScaffoldAgent (Project Generator)"
        ))
        
        db_url = "sqlite:///./app.db"
        if ctx.database_type == "postgres":
            db_url = f"postgresql://user:password@localhost:5432/{ctx.project_name_slug}"
        elif ctx.database_type == "mysql":
            db_url = f"mysql+pymysql://user:password@localhost:3306/{ctx.project_name_slug}"

        files.append(ScaffoldFile(
            path=".env.example",
            content=f"PROJECT_NAME=\"{ctx.project_name}\"\nDATABASE_URL=\"{db_url}\"\nDEBUG=True\n",
            language="text", generated_by="ScaffoldAgent (Project Generator)"
        ))
        return files

    def _docs_files(self, ctx: GenerationContext) -> List[ScaffoldFile]:
        files = []
        if ctx.architecture_summary:
            files.append(ScaffoldFile(
                path="docs/architecture.md",
                content=f"# Architecture\n\n{ctx.architecture_summary}\n",
                language="markdown", generated_by="ArchitectureAgent"
            ))
        if ctx.sql_schema:
            files.append(ScaffoldFile(
                path="docs/database.md",
                content=f"# Database Design\n\nSQL schema for {ctx.project_name}.\n\n```sql\n{ctx.sql_schema}\n```\n",
                language="markdown", generated_by="DatabaseAgent"
            ))
        files.append(ScaffoldFile(
            path="docs/api.md",
            content=(
                "# API Reference\n\n## Endpoints\n\n"
                + "\n".join(f"### `{r.method} {r.path}`\n{r.description}\n" for r in ctx.api_routes)
                if ctx.api_routes else "# API Reference\n\nNo routes defined yet.\n"
            ),
            language="markdown", generated_by="ScaffoldAgent (Project Generator)"
        ))
        return files

    def _backend_files(self, ctx: GenerationContext, v: dict) -> List[ScaffoldFile]:
        files = [
            ScaffoldFile(path="backend/app/main.py", content=self._render("fastapi_main.py.template", v) if "fastapi_main.py.template" in self._loader.list_templates() else "from fastapi import FastAPI\n\napp = FastAPI()\n", language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/database.py", content=self._render("fastapi_database.py.template", v) if "fastapi_database.py.template" in self._loader.list_templates() else "from sqlalchemy import create_engine\nfrom sqlalchemy.orm import sessionmaker\n", language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/requirements.txt", content="fastapi\nuvicorn\nsqlalchemy\npydantic\npydantic-settings\nalembic\n", language="text", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/__init__.py", content='"""Application Root."""\n', language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/api/__init__.py", content='"""API Routers."""\n', language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/models/__init__.py", content='"""SQLAlchemy Models."""\n', language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/schemas/__init__.py", content='"""Pydantic Schemas."""\n', language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/services/__init__.py", content='"""Business Logic Services."""\n', language="python", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="backend/app/core/__init__.py", content='"""Core Configuration."""\n', language="python", generated_by="ScaffoldAgent (Project Generator)"),
        ]

        db_url = "sqlite:///./app.db"
        if ctx.database_type == "postgres":
            db_url = f"postgresql://user:password@localhost:5432/{ctx.project_name_slug}"
        elif ctx.database_type == "mysql":
            db_url = f"mysql+pymysql://user:password@localhost:3306/{ctx.project_name_slug}"

        files.append(
            ScaffoldFile(
                path="backend/app/core/config.py",
                content=(
                    "from pydantic_settings import BaseSettings\n\n"
                    "class Settings(BaseSettings):\n"
                    f"    PROJECT_NAME: str = \"{ctx.project_name}\"\n"
                    f"    DATABASE_URL: str = \"{db_url}\"\n"
                    "    DEBUG: bool = True\n\n"
                    "    class Config:\n        env_file = \".env\"\n\n"
                    "settings = Settings()\n"
                ),
                language="python", generated_by="ScaffoldAgent (Project Generator)"
            )
        )

        for entity in ctx.entities:
            name = entity.name.lower()
            camel_name = "".join(x.capitalize() or "_" for x in name.split("_"))
            
            # Model
            model_fields = []
            for attr in entity.attributes:
                model_fields.append(f"    {attr['name']} = Column(String)  # Type from {attr['type']}")
            model_content = f"from sqlalchemy import Column, String, Integer\nfrom app.database import Base\n\nclass {camel_name}(Base):\n    __tablename__ = '{name}s'\n" + "\n".join(model_fields)
            files.append(ScaffoldFile(path=f"backend/app/models/{name}.py", content=model_content, language="python", generated_by="ScaffoldAgent (Project Generator)"))

            # Schema
            schema_fields = []
            for attr in entity.attributes:
                schema_fields.append(f"    {attr['name']}: str")
            schema_content = f"from pydantic import BaseModel\n\nclass {camel_name}Base(BaseModel):\n" + "\n".join(schema_fields) + f"\n\nclass {camel_name}Create({camel_name}Base):\n    pass\n\nclass {camel_name}Response({camel_name}Base):\n    id: int\n\n    class Config:\n        orm_mode = True\n"
            files.append(ScaffoldFile(path=f"backend/app/schemas/{name}.py", content=schema_content, language="python", generated_by="ScaffoldAgent (Project Generator)"))
            
            # Service
            service_content = f"from sqlalchemy.orm import Session\nfrom app.models.{name} import {camel_name}\nfrom app.schemas.{name} import {camel_name}Create\n\nclass {camel_name}Service:\n    @staticmethod\n    def get_all(db: Session):\n        return db.query({camel_name}).all()\n\n    @staticmethod\n    def create(db: Session, obj_in: {camel_name}Create):\n        db_obj = {camel_name}(**obj_in.dict())\n        db.add(db_obj)\n        db.commit()\n        db.refresh(db_obj)\n        return db_obj\n"
            files.append(ScaffoldFile(path=f"backend/app/services/{name}_service.py", content=service_content, language="python", generated_by="ScaffoldAgent (Project Generator)"))

            # Router
            files.append(ScaffoldFile(
                path=f"backend/app/api/{name}_router.py",
                content=(
                    f"from fastapi import APIRouter, Depends\nfrom sqlalchemy.orm import Session\nfrom app.database import get_db\nfrom app.schemas.{name} import {camel_name}Create, {camel_name}Response\nfrom app.services.{name}_service import {camel_name}Service\n\nrouter = APIRouter(prefix=\"/{name}s\", tags=[\"{camel_name}\"])\n\n"
                    f"@router.get(\"/\", response_model=list[{camel_name}Response])\nasync def list_{name}s(db: Session = Depends(get_db)):\n    return {camel_name}Service.get_all(db)\n\n"
                    f"@router.post(\"/\", response_model={camel_name}Response)\nasync def create_{name}(data: {camel_name}Create, db: Session = Depends(get_db)):\n    return {camel_name}Service.create(db, data)\n"
                ),
                language="python", generated_by="ScaffoldAgent (Project Generator)"
            ))

        return files

    def _frontend_files(self, ctx: GenerationContext, v: dict) -> List[ScaffoldFile]:
        return [
            ScaffoldFile(path="frontend/src/App.tsx", content=self._render("react_app.tsx.template", v) if "react_app.tsx.template" in self._loader.list_templates() else f"export default function App() {{ return <div>Welcome to {ctx.project_name}</div>; }}", language="typescript", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="frontend/package.json", content=self._render("package.json.template", v) if "package.json.template" in self._loader.list_templates() else "{\n  \"name\": \"frontend\",\n  \"version\": \"1.0.0\"\n}", language="json", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="frontend/src/main.tsx", content=(
                "import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\n"
                "ReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n"
            ), language="typescript", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="frontend/src/index.css", content=(
                "* { box-sizing: border-box; margin: 0; padding: 0; }\n"
                "body { font-family: 'Inter', sans-serif; background: #0f172a; color: #f1f5f9; }\n"
            ), language="css", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="frontend/tsconfig.json", content=json.dumps({
                "compilerOptions": {"target": "ES2020", "useDefineForClassFields": True,
                                    "lib": ["ES2020", "DOM"], "module": "ESNext",
                                    "skipLibCheck": True, "moduleResolution": "bundler",
                                    "allowImportingTsExtensions": True, "resolveJsonModule": True,
                                    "isolatedModules": True, "noEmit": True, "jsx": "react-jsx",
                                    "strict": True},
                "include": ["src"], "references": [{"path": "./tsconfig.node.json"}]
            }, indent=2), language="json", generated_by="ScaffoldAgent (Project Generator)"),
        ]

    def _database_files(self, ctx: GenerationContext) -> List[ScaffoldFile]:
        sql = ctx.sql_schema or "-- Auto‑generated schema placeholder\nCREATE TABLE IF NOT EXISTS app_health (\n    id INTEGER PRIMARY KEY,\n    status TEXT NOT NULL DEFAULT 'ok'\n);\n"
        return [
            ScaffoldFile(path="database/schema.sql", content=sql, language="sql", generated_by="DatabaseAgent"),
        ]

    def _scripts_files(self, ctx: GenerationContext, v: dict) -> List[ScaffoldFile]:
        slug = ctx.project_name_slug
        return [
            ScaffoldFile(path="scripts/setup.sh", content=(
                "#!/bin/bash\nset -e\necho '🔧 Setting up backend...'\ncd backend && pip install -r requirements.txt && cd ..\n"
                "echo '🔧 Setting up frontend...'\ncd frontend && npm install && cd ..\necho '✅ Setup complete!'\n"
            ), language="bash", generated_by="ScaffoldAgent (Project Generator)"),
            ScaffoldFile(path="scripts/run.sh", content=(
                "#!/bin/bash\necho '🚀 Starting backend...'\ncd backend && uvicorn app.main:app --reload --port 8000 &\n"
                "echo '🚀 Starting frontend...'\ncd frontend && npm run dev\n"
            ), language="bash", generated_by="ScaffoldAgent (Project Generator)"),
        ]

    def _github_files(self, ctx: GenerationContext, v: dict) -> List[ScaffoldFile]:
        return [
            ScaffoldFile(path=".github/workflows/ci.yml", content=(
                "name: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\n"
                "jobs:\n  backend:\n    runs-on: ubuntu-latest\n    steps:\n"
                "      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n"
                "        with:\n          python-version: '3.12'\n"
                "      - run: pip install -r backend/requirements.txt\n"
                "      - run: python -m pytest backend/ -v --tb=short || true\n\n"
                "  frontend:\n    runs-on: ubuntu-latest\n    steps:\n"
                "      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n"
                "        with:\n          node-version: '20'\n"
                "      - run: cd frontend && npm install\n      - run: cd frontend && npm run build || true\n"
            ), language="yaml", generated_by="ScaffoldAgent (Project Generator)"),
        ]

    def _generated_summary(self, ctx: GenerationContext, files: List[ScaffoldFile]) -> List[ScaffoldFile]:
        summary = {
            "project_name": ctx.project_name,
            "generated_on": str(date.today()),
            "frontend": ctx.frontend_type,
            "backend": ctx.backend_type,
            "database": ctx.database_type,
            "authentication": ctx.authentication,
            "agents_completed": ["Requirements", "Architecture", "Database", "Documentation", "Scaffold"],
            "total_files": len(files) + 1,
            "total_directories": 10,
            "entities": [e.name for e in ctx.entities],
            "api_routes": [{"method": r.method, "path": r.path} for r in ctx.api_routes],
        }
        return [
            ScaffoldFile(
                path="generated/project_summary.json",
                content=json.dumps(summary, indent=2),
                language="json", generated_by="ScaffoldAgent (Project Generator)"
            ),
        ]
